version: "3.8"

services:
  php-fpm:
    container_name: php-fpm-${COMPOSE_PROJECT_NAME}
    build:
      context: ./../
      dockerfile: ./macos-docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/
    ports:
      - ${NGINX_HOST_HTTP_PORT}:8080
    networks:
      - client-server

#  nginx:
#    container_name: nginx-${COMPOSE_PROJECT_NAME}
#    build:
#      context: ./nginx
#    ports:
#      - ${NGINX_HOST_HTTP_PORT}:80
#    volumes:
#      - ..:/var/www:rw
#    depends_on:
#      - php-fpm

  postgres:
    container_name: postgres-${COMPOSE_PROJECT_NAME}
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw

volumes:
  db_data: